### PR TITLE
Interleaved support

### LINKED ISSUE #46: add support for interleaved PE fastq
It would be nice for bwameth to accept interleaved reads like bwa, so you can adapter trim on a pipe (like bwakit).  Would you entertain a PR to that effect?

### PR DESCRIPTION
**Pull request by bwlang**
@brentp  I'm just getting ready to test... but i thought I'd ask for your feedback on the approach if you're still up.
It's a bit strange that i'm only using the -p flag to decide , but sniffing is easier than passing around the flag 
fixes #46

### CODE REVIEW

**Comment by brentp** [comment]
on quick look. seems reasonable. you'll have to adjust readi so it's e.g. `readi % 2` or something.

**Comment by bwlang** [comment]
I tested like this:
<code>
./bwameth_orig.py --reference /mnt/galaxy/data/genome/mc_controls/bwameth_index/mc_controls/mc_controls.fa  tiny_Lot21-8.6-ug-1.1.fastq tiny_Lot21-8.6-ug-1.2.fastq | sambamba view -S -f bam /dev/stdin | sambamba sort -o  tiny_Lot21-8.6-ug-1.2files.controls_orig.bam /dev/stdin
</code>
and
<code>
./bwameth.py --reference /mnt/galaxy/data/genome/mc_controls/bwameth_index/mc_controls/mc_controls.fa  tiny_Lot21-8.6-ug-1.1.fastq tiny_Lot21-8.6-ug-1.2.fastq | sambamba view -S -f bam /dev/stdin | sambamba sort -o  tiny_Lot21-8.6-ug-1.2files.controls.bam /dev/stdin
</code>

diff tiny_Lot21-8.6-ug-1.2files.controls_orig.sam tiny_Lot21-8.6-ug-1.2files.controls.sam produced no output (did not break 2 files mode)


./bwameth.py --reference /mnt/galaxy/data/genome/mc_controls/bwameth_index/mc_controls/mc_controls.fa -p tiny_Lot21-8.6-ug-1.interleaved.fastq  | sambamba view -S -f bam /dev/stdin | sambamba sort -o tiny_Lot21-8.6-ug-1.interleaved.controls.bam /dev/stdin

checked that the idxstats all match and reads match up (except rg which is expeted to change)
diff <(cut -f 1-9 tiny_Lot21-8.6-ug-1.interleaved.mapped.sam) <(cut -f 1-9 tiny_Lot21-8.6-ug-1.2files.controls_orig.sam)
(no output)

**Comment by brentp** [comment]
looks good.
is the flag needed since you're detecting interleaved?

**Comment by bwlang** [comment]
The flag is only used for the paired-end option passed to bwa_mem and the RG logic.
I could detect on the first execution and re-detect on the c2t exeuction to avoid the flag if you like. I don't think its surprising that one specifies an interleaved flag... it's just a bit weird that it's not used globally.

Let me know how you want to go.

**Comment by brentp** [comment]
looks good to me. let me know when you're ready. I just notice you have "producting".

**Comment by bwlang** [comment]
I think the current implementation is fine - i'm ready to merge it if you are.

**Comment by brentp** [comment]
thanks!

**Pull request merged**
